manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/lynnlee0522 # 修改这里

  projects:
  - name: zmk_offical
    remote: zmkfirmware
    revision: main
    import: app/west.yml

  self:
    path: config
